name: CI-BlackDuck-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
    
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@v1.13.0
        
        env:
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
          DETECT_PROJECT_VERSION_NAME: ${{ github.event.repository.default_branch }}
          DETECT_ACCURACY_REQUIRED: NONE
          
        with:
          blackduck_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_fixpr_enabled: true
          blackduck_prComment_enabled: true
          blackduck_reports_sarif_create: true
          blackduck_upload_sarif_report: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: SRM Import
        uses: codedx/codedx-github-action@v1.3.0
        with:
          server-url: ${{ secrets.SRM_URL }}
          api-key: ${{ secrets.SRM_APIKEY }}
          auto-create-project: true
          project-name: ${{ github.event.repository.name }}
          base-branch-name: ${{ github.event.repository.default_branch }}
          target-branch-name: ${{ github.ref_name }}
          source-and-binaries-glob: './**'
          wait-for-completion: true
          
          
          