# This is a basic workflow to help you get started with Actions

name: black Duck Security Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch -
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    #runs-on: [self-hosted]
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Synopsys Action
        uses: synopsys-sig/synopsys-action@v1.13.0
        env:
          DETECT_PROJECT_NAME: blackduck-security-scan
          DETECT_PROJECT_VERSION_NAME: development
          DETECT_ACCURACY_REQUIRED: NONE
        with:
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}

          # Optional parameter. By default, pushes will initiate a full "intelligent" scan and pull requests
          # will initiate a rapid scan.
          blackduck_scan_full: true
          # Required parameter if blackduck_automation_fixpr is enabled
          # Make sure GITHUB_TOKEN have appropriate permissions
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Optional parameter. By default, create fix pull requests if vulnerabilities are reported
          # Passing false will disable fix pull request creation 
          blackduck_automation_fixpr: false
          # Optional parameter. The values could be. ALL|NONE|BLOCKER|CRITICAL|MAJOR|MINOR|OK|TRIVIAL|UNSPECIFIED
          # Single parameter
          
        - name: SRM Import
          uses: codedx/codedx-github-action@v1.3.0
          with:
            server-url: ${{ secrets.SRM_URL }}
            api-key: ${{ secrets.SRM_APIKEY }}
            auto-create-project: true
            project-name: blackduck-security-scan
            base-branch-name: development
            target-branch-name: development
            wait-for-completion: false
